version: '2'
services:
    gitlab:
      image: 'twang2218/gitlab-ce-zh:10.0'
      container_name: gitlab
      restart: always
      hostname: 'gitlab.xxx.com'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          # sudo -e /etc/gitlab/gitlab.rb
          external_url 'http://gitlab.xxx.com'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'

          gitlab_rails['gitlab_email_enabled'] = false
          # gitlab_rails['gitlab_email_from'] = 'example@example.com'
          # gitlab_rails['gitlab_email_display_name'] = 'Example'
          # gitlab_rails['gitlab_email_reply_to'] = 'noreply@example.com'
          # gitlab_rails['gitlab_email_subject_suffix'] = ''

          # gitlab_rails['smtp_enable'] = true
          # gitlab_rails['smtp_address'] = "smtp.server"
          # gitlab_rails['smtp_port'] = 465
          # gitlab_rails['smtp_user_name'] = "smtp user"
          # gitlab_rails['smtp_password'] = "smtp password"
          # gitlab_rails['smtp_domain'] = "example.com"
          # gitlab_rails['smtp_authentication'] = "login"
          # gitlab_rails['smtp_enable_starttls_auto'] = true
          # gitlab_rails['smtp_tls'] = false

          # user['git_user_name'] = "GitLab"
          # user["git_user_email"] = "xxx@163.com"

          # gitlab_rails['backup_path'] = "/var/opt/gitlab/backups"
          # gitlab_rails['backup_keep_time'] = 259200
          # gitlab_rails['backup_archive_permissions'] = 0644
      ports:
        - '8000:80'
        - '4433:443'
        # modify .ssh/config
        - '222:22'
      volumes:
        - ${HOME}/softwares/gitlab/conf:/etc/gitlab
        - ${HOME}/softwares/gitlab/data:/var/opt/gitlab
        - ${HOME}/softwares/gitlab/logs:/var/log/gitlab
